// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDagqpuwjYRRzFRfjPt03QGgWNaWTVzr9s',
    appId: '1:394669289708:web:11c331015629e8a06e35c9',
    messagingSenderId: '394669289708',
    projectId: 'gerenciecoisas',
    authDomain: 'gerenciecoisas.firebaseapp.com',
    storageBucket: 'gerenciecoisas.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-IBx0S26_BOhakLxMYYxfQWNnxjyp_n4',
    appId: '1:394669289708:android:8a0e2a30dd2a79a86e35c9',
    messagingSenderId: '394669289708',
    projectId: 'gerenciecoisas',
    storageBucket: 'gerenciecoisas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6GWZcX6K2hqNEnGy8Z3iI5YislP_5CgU',
    appId: '1:394669289708:ios:437253b1b24ecd396e35c9',
    messagingSenderId: '394669289708',
    projectId: 'gerenciecoisas',
    storageBucket: 'gerenciecoisas.firebasestorage.app',
    iosBundleId: 'com.example.gerencieCoisas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6GWZcX6K2hqNEnGy8Z3iI5YislP_5CgU',
    appId: '1:394669289708:ios:437253b1b24ecd396e35c9',
    messagingSenderId: '394669289708',
    projectId: 'gerenciecoisas',
    storageBucket: 'gerenciecoisas.firebasestorage.app',
    iosBundleId: 'com.example.gerencieCoisas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDagqpuwjYRRzFRfjPt03QGgWNaWTVzr9s',
    appId: '1:394669289708:web:af19f162fdcf9fe36e35c9',
    messagingSenderId: '394669289708',
    projectId: 'gerenciecoisas',
    authDomain: 'gerenciecoisas.firebaseapp.com',
    storageBucket: 'gerenciecoisas.firebasestorage.app',
  );
}
